### ISSUE TITLE
Problem - PSME Compute Agent encrypt and decrypt functions fail

### ISSUE THREAD

**Issue by housemic** [intel/intelRSD#55] opened 2018-03-09 08:42 UTC
Dear intel -
the issue is related to #48,
Questions how PSME compute agent send IPMI commands to BMC AST2400 2500 and remove CY7C65215 ,

../../agent/compute/psme-key and /etc/psme/psme-key are the same files,
but PSME Compute Agent encrypt and decrypt functions still fail,
the detail steps are in the following comment,
Please support, thank you.
House

**Comment by housemic** [comment] 2018-03-09 08:45
Dear intel -
this is my detail actions -



PSME server (Grantley) - PCIe LAN IP : 192.168.1.135 (DHCP)

BMC 2 (Purley) - BMC network IP : 192.168.1.106 (DHCP)




I modify settings and code to enable functions of encrypt and decrypt :

-----------------------------------------------------------


ls -al /etc/psme/psme-key

-rw------- 1 root root 8  鈭? 22 23:51 /etc/psme/psme-key


sudo rm /etc/psme/psme-key


ls -al /etc/psme/psme-key
ls: cannot access '/etc/psme/psme-key': No such file or directory



cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/build/bin


sudo ./encrypt root
Key file not found: /etc/psme/psme-key
Creating key file: /etc/psme/psme-key
8B6D1CE58E4B94F3



ls -al /etc/psme/psme-key
-rw------- 1 root root 8  銝?  9 17:47 /etc/psme/psme-key


-----------------------------------------------------------




cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/application

sudo cp /etc/psme/psme-key ./


ls -la psme-key
-rw------- 1 root root 8  銝?  9 17:48 psme-key



-----------------------------------------------------------




-----------------------------------------------------------




-----------------------------------------------------------

cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute

use root / root (encrypted hash values) as BMC username / password :

sudo gedit configuration.json

-----------------------------------------------------------

    "managers": [
        {
            "slot" : 1,
            "switchPortIdentifier" : "sw0p37",
            "ipv4": "192.168.1.106",
            "username": "8B6D1CE58E4B94F3",
            "password": "8B6D1CE58E4B94F3",
            "port": 623,
            "serialConsoleEnabled": true
        }
    ],


-----------------------------------------------------------



-----------------------------------------------------------

cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute/src


sudo gedit main.cpp


-----------------------------------------------------------

BmcCollection load_bmcs(const json::Value& config) {
    BmcCollection bmcs{};
    Bmc::Duration state_update_interval = GpioManager::get_instance()->get_minimal_update_interval();
    for (const auto& manager : config["managers"]) {
        auto slot = manager["slot"].as_uint();
        auto read_presence_fn = [slot]() {
            log_debug(GET_LOGGER("compute-agent"), "reading presence on slot: " << slot);
/* OEM-HC-2018-02-21-00
            return GpioManager::get_instance()->is_present(uint8_t(slot));
*/
            return true;
        };

        ConnectionData connection{};
        connection.set_ip_address(manager["ipv4"].as_string());

        connection.set_username(decrypt_value(manager["username"].as_string()));
        connection.set_password(decrypt_value(manager["password"].as_string()));

/* OEM-HC-2018-02-21-01
        connection.set_username(manager["username"].as_string());
        connection.set_password(manager["password"].as_string());
*/



-----------------------------------------------------------



-----------------------------------------------------------


cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/build


cmake ..

-----------------------------------------------------------

make psme-compute -j8

[100%] Linking CXX executable ../../../bin/psme-compute
[100%] Built target psme-compute


-----------------------------------------------------------

ls -al bin/psme-compute
-rwxrwxr-x 1 user user 7507600  銝?  9 17:50 bin/psme-compute



-----------------------------------------------------------


sudo ipmitool -I lan -U root -P root -H 192.168.1.106 raw 0x06 0x01
[sudo] password for user: 
 20 01 00 12 02 bf af 2b 00 00 00 e0 16 12 00


-----------------------------------------------------------

sudo ipmitool -I lan -U root -P root -H 192.168.1.106 lan print
Set in Progress         : Set Complete
Auth Type Support       : MD5 
Auth Type Enable        : Callback : MD5 
                        : User     : MD5 
                        : Operator : MD5 
                        : Admin    : MD5 
                        : OEM      : MD5 
IP Address Source       : DHCP Address
IP Address              : 192.168.1.106
Subnet Mask             : 255.255.255.0
MAC Address             : 4c:38:d5:00:c2:4a
SNMP Community String   : Hyve
IP Header               : TTL=0x40 Flags=0x40 Precedence=0x00 TOS=0x10
BMC ARP Control         : ARP Responses Enabled, Gratuitous ARP Disabled
Gratituous ARP Intrvl   : 0.0 seconds
Default Gateway IP      : 192.168.1.1
Default Gateway MAC     : 00:22:4d:a9:11:5b
Backup Gateway IP       : 0.0.0.0
Backup Gateway MAC      : 00:00:00:00:00:00
802.1q VLAN ID          : Disabled
802.1q VLAN Priority    : 0
RMCP+ Cipher Suites     : 0,1,2,3,6,7,8,11,12,15,16,17
Cipher Suite Priv Max   : caaaaaaaaaaaXXX
                        :     X=Cipher Suite Unused
                        :     c=CALLBACK
                        :     u=USER
                        :     o=OPERATOR
                        :     a=ADMIN
                        :     O=OEM
Bad Password Threshold  : 0
Invalid password disable: no
Attempt Count Reset Int.: 0
User Lockout Interval   : 0



-----------------------------------------------------------

-----------------------------------------------------------

cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/build/bin


./psme-rest-server ../../application/configuration.json
 


-----------------------------------------------------------

cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/build/bin


./psme-compute ../../agent/compute/configuration.json




-----------------------------------------------------------


user@psme1:~$ cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/build/bin
user@psme1:~/IntelRSD/intelRSD-2-2-mod-01/PSME/build/bin$ ./psme-compute ../../agent/compute/configuration.json
2018-03-09 18:06:07.549608469 - INFO  - agent - Method getChassisInfo has been registered
2018-03-09 18:06:07.549733641 - INFO  - agent - Method getCollection has been registered
2018-03-09 18:06:07.549776470 - INFO  - agent - Method getDriveInfo has been registered
2018-03-09 18:06:07.549802540 - INFO  - agent - Method getManagersCollection has been registered
2018-03-09 18:06:07.549831407 - INFO  - agent - Method getTasksCollection has been registered
2018-03-09 18:06:07.549854651 - INFO  - agent - Method getManagerInfo has been registered
2018-03-09 18:06:07.549877250 - INFO  - agent - Method getTaskInfo has been registered
2018-03-09 18:06:07.549899655 - INFO  - agent - Method getTaskResultInfo has been registered
2018-03-09 18:06:07.549927212 - INFO  - agent - Method getMemoryInfo has been registered
2018-03-09 18:06:07.549949981 - INFO  - agent - Method getNetworkInterfaceInfo has been registered
2018-03-09 18:06:07.549974562 - INFO  - agent - Method getNetworkDeviceInfo has been registered
2018-03-09 18:06:07.549997531 - INFO  - agent - Method getNetworkDeviceFunctionInfo has been registered
2018-03-09 18:06:07.550026184 - INFO  - agent - Method getProcessorInfo has been registered
2018-03-09 18:06:07.550049117 - INFO  - agent - Method getStorageControllerInfo has been registered
2018-03-09 18:06:07.550077536 - INFO  - agent - Method getStorageSubsystemInfo has been registered
2018-03-09 18:06:07.550100803 - INFO  - agent - Method getComputerSystemInfo has been registered
2018-03-09 18:06:07.550171286 - INFO  - agent - Method setComponentAttributes has been registered
2018-03-09 18:06:07.550258969 - INFO  - agent - Method getTrustedModuleInfo has been registered
2018-03-09 18:06:07.550328703 - INFO  - agent - Method deleteTask has been registered
2018-03-09 18:06:07.550388100 - INFO  - agent - Method getMetricDefinitionInfo has been registered
2018-03-09 18:06:07.550478967 - INFO  - agent - Method getMetricDefinitionsCollection has been registered
2018-03-09 18:06:07.550548972 - INFO  - agent - Method getMetrics has been registered
2018-03-09 18:06:07.550608242 - INFO  - agent - Method getFanInfo has been registered
2018-03-09 18:06:07.550692834 - INFO  - agent - Method getPowerZoneInfo has been registered
2018-03-09 18:06:07.550770721 - INFO  - agent - Method getThermalZoneInfo has been registered
2018-03-09 18:06:07.557569707 - INFO  - compute-agent - MANUAL PSME BUILD; Built 17:50:34, 09-03-2018
2018-03-09 18:06:07.557694221 - DEBUG - configuration - Added file ../../agent/compute/configuration.json
2018-03-09 18:06:07.557750480 - WARN  - configuration - Cannot load default file
2018-03-09 18:06:07.557772525 - INFO  - configuration - Load file
2018-03-09 18:06:07.557837136 - INFO  - configuration - Loaded file ../../agent/compute/configuration.json
2018-03-09 18:06:07.557877608 - INFO  - configuration - Load internal defaults
2018-03-09 18:06:07.558041357 - INFO  - compute-agent - JSON Schema load!
2018-03-09 18:06:07.562238143 - INFO  - compute-agent - 
Running SDV PSME Compute Agent.
2018-03-09 18:06:07.562346367 - DEBUG - registration - Registration url: http://localhost:8383 interval: 3s
2018-03-09 18:06:07.562397057 - INFO  - eventing - Starting EventDispatcher thread...
2018-03-09 18:06:07.562418972 - WARN  - db - Cannot check /var/opt/psme/check_raWlBX:: Permission denied
2018-03-09 18:06:07.562603464 - INFO  - db - Database in temporary /tmp/database_9SGQK5
2018-03-09 18:06:07.563046124 - INFO  - default - Service UUID 90586af4-f5c9-11e7-b8b5-1f87effca6f1.
2018-03-09 18:06:07.569968047 - DEBUG - registration - Registration response: {"ipv4address":"localhost","port":5567,"version":"1.0.0"}
2018-03-09 18:06:07.570244037 - INFO  - registration - Agent has been registered to http://localhost:8383, interval 3s, rest runs for 0s
2018-03-09 18:06:07.570259553 - INFO  - eventing - Sending AMC notifications enabled.
Invalid user name
Error: Unable to establish LAN session
Error: Unable to establish IPMI v1.5 / RMCP session
2018-03-09 18:06:10.578495933 - INFO  - agent - gpio minimal read interval: 5000ms
2018-03-09 18:06:10.578820145 - DEBUG - worker - Schedule periodic task state_update:192.168.1.106:0 delay: 0 period: 5000000000
2018-03-09 18:06:10.578907136 - DEBUG - worker - Schedule periodic task power_state_boot_options:192.168.1.106:1 delay: 0 period: 5000000000
2018-03-09 18:06:10.578969340 - DEBUG - worker - Schedule self sheduling task telemetry_runner:192.168.1.106:2 delay: 0
2018-03-09 18:06:10.578982691 - DEBUG - default - Waiting for interrupt signal...
2018-03-09 18:06:10.579149830 - DEBUG - compute-agent - reading presence on slot: 1
2018-03-09 18:06:10.579198770 - INFO  - bmc -  (192.168.1.106:623) in state: ABSENT received event: Inserted
2018-03-09 18:06:10.579208162 - INFO  - bmc -  (192.168.1.106:623) state transition ABSENT --> OFFLINE caused by Inserted
2018-03-09 18:06:10.579216528 - INFO  - bmc -  (192.168.1.106:623) transition status: OK
2018-03-09 18:06:10.579223537 - DEBUG - compute-agent - reading online state...
2018-03-09 18:06:10.599004548 - DEBUG - compute-agent - reading online state error: Can't open IPMI connection.
2018-03-09 18:06:13.577845272 - DEBUG - registration - Rest runs for 6s
2018-03-09 18:06:14.383698229 - DEBUG - command-server - RPC Method call: getManagersCollection
2018-03-09 18:06:14.383722826 - DEBUG - rpc - Getting collection of managers.
2018-03-09 18:06:14.384097902 - DEBUG - command-server - RPC Method call: getTasksCollection
2018-03-09 18:06:14.384111921 - DEBUG - compute-agent - Getting collection of tasks
2018-03-09 18:06:14.384406539 - DEBUG - command-server - RPC Method call: getMetricDefinitionsCollection
2018-03-09 18:06:14.384420257 - DEBUG - compute-agent - Getting collection of metric definitions
2018-03-09 18:06:14.384734122 - DEBUG - command-server - RPC Method call: getMetrics
2018-03-09 18:06:14.384771485 - DEBUG - compute-agent - Getting collection of metrics
Invalid user name
Error: Unable to establish LAN session
Error: Unable to establish IPMI v1.5 / RMCP session
2018-03-09 18:06:15.578966675 - DEBUG - compute-agent - reading presence on slot: 1
2018-03-09 18:06:15.578978970 - DEBUG - compute-agent - reading online state...
2018-03-09 18:06:15.587583934 - DEBUG - compute-agent - reading online state error: Can't open IPMI connection.
2018-03-09 18:06:16.578873682 - DEBUG - registration - Rest runs for 9s
2018-03-09 18:06:19.579400016 - DEBUG - registration - Rest runs for 12s
Invalid user name
Error: Unable to establish LAN session
Error: Unable to establish IPMI v1.5 / RMCP session


-----------------------------------------------------------

**Comment by tbykowsk** [comment] 2018-03-09 12:11
Hi @housemic,

In above steps you copied `psme-key` to `/home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/application`

> cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/application
> 
> sudo cp /etc/psme/psme-key ./

but you should copy it to `/home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute`.

I think it might be less confusing, if you copied `/home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute/configuration.json` to `/etc/psme` and run the agent using `./psme-compute /etc/psme/configuration.json`.

**Comment by housemic** [comment] 2018-03-13 08:25
Dear  tbykowsk ,
I copy psme-key from /etc/psme/ to /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute/.
still has the same error message  - Invalid user name,
Is the issue related to encrypt / decrypt function ? thank you.
House

the followings are my detail steps -


PSME server (Grantley) - PCIe LAN IP : 192.168.1.135 (DHCP)

BMC 2 (Purley) - BMC network IP : 192.168.1.106 (DHCP)




I modify settings and code to enable functions of encrypt and decrypt :

-----------------------------------------------------------



[sudo] password for user: 
user@psme1:/etc/psme$ ls -al
total 24
drwxr-xr-x   3 root root  4096  銝? 13 01:57 .
drwxr-xr-x 135 root root 12288  鈭? 12 22:15 ..
drwxr-xr-x   2 root root  4096  銝  15 17:05 certs
-rw-r--r-T   1 root root    47  銝  15 17:07 service_uuid.json


-----------------------------------------------------------


user@psme1:~/IntelRSD/intelRSD-2-2-mod-01/PSME/build/bin$ ./encrypt root
Key file not found: /etc/psme/psme-key
Creating key file: /etc/psme/psme-key
Error: Error with opening keyfile for write.
user@psme1:~/IntelRSD/intelRSD-2-2-mod-01/PSME/build/bin$ sudo ./encrypt root
[sudo] password for user: 
Key file not found: /etc/psme/psme-key
Creating key file: /etc/psme/psme-key
41CA7FDE224A8248


-----------------------------------------------------------


user@psme1:/etc/psme$ ls -la
total 28
drwxr-xr-x   3 root root  4096  銝? 13 02:01 .
drwxr-xr-x 135 root root 12288  鈭? 12 22:15 ..
drwxr-xr-x   2 root root  4096  銝  15 17:05 certs
-rw-------   1 root root     8  銝? 13 02:01 psme-key
-rw-r--r-T   1 root root    47  銝  15 17:07 service_uuid.json

-----------------------------------------------------------



user@psme1:~/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute$ sudo cp /etc/psme/psme-key ./
[sudo] password for user: 
user@psme1:~/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute$ pwd
/home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute
user@psme1:~/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute$ ls -la psme-key
-rw------- 1 root root 8  銝? 13 02:02 psme-key


-----------------------------------------------------------


cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute

use root / root (encrypted hash values) as BMC username / password :

sudo gedit configuration.json

-----------------------------------------------------------

    "managers": [
        {
            "slot" : 1,
            "switchPortIdentifier" : "sw0p37",
            "ipv4": "192.168.1.106",
            "username": "41CA7FDE224A8248",
            "password": "41CA7FDE224A8248",
            "port": 623,
            "serialConsoleEnabled": true
        }
    ],


-----------------------------------------------------------




-----------------------------------------------------------


-----------------------------------------------------------

cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute/src


sudo gedit main.cpp


-----------------------------------------------------------

BmcCollection load_bmcs(const json::Value& config) {
    BmcCollection bmcs{};
    Bmc::Duration state_update_interval = GpioManager::get_instance()->get_minimal_update_interval();
    for (const auto& manager : config["managers"]) {
        auto slot = manager["slot"].as_uint();
        auto read_presence_fn = [slot]() {
            log_debug(GET_LOGGER("compute-agent"), "reading presence on slot: " << slot);
/* OEM-HC-2018-02-21-00
            return GpioManager::get_instance()->is_present(uint8_t(slot));
*/
            return true;
        };

        ConnectionData connection{};
        connection.set_ip_address(manager["ipv4"].as_string());

        connection.set_username(decrypt_value(manager["username"].as_string()));
        connection.set_password(decrypt_value(manager["password"].as_string()));

/* OEM-HC-2018-02-21-01
        connection.set_username(manager["username"].as_string());
        connection.set_password(manager["password"].as_string());
*/



-----------------------------------------------------------




-----------------------------------------------------------


cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/build


cmake ..

-----------------------------------------------------------

make psme-compute -j8

[100%] Linking CXX executable ../../../bin/psme-compute
[100%] Built target psme-compute


-----------------------------------------------------------

ls -al bin/psme-compute
-rwxrwxr-x 1 user user 7507600  銝? 13 19:11 bin/psme-compute




-----------------------------------------------------------


sudo ipmitool -I lan -U root -P root -H 192.168.1.106 raw 0x06 0x01
[sudo] password for user: 
 20 01 00 12 02 bf af 2b 00 00 00 e0 16 12 00


-----------------------------------------------------------



-----------------------------------------------------------


-----------------------------------------------------------

cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/build/bin


./psme-rest-server ../../application/configuration.json
 


-----------------------------------------------------------

cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/build/bin


./psme-compute ../../agent/compute/configuration.json




-----------------------------------------------------------



-----------------------------------------------------------

user@psme1:~/IntelRSD/intelRSD-2-2-mod-01/PSME/build$ sudo ipmitool -I lan -U root -P root -H 192.168.1.106 raw 0x06 0x01
 20 01 00 12 02 bf af 2b 00 00 00 e0 16 12 00
user@psme1:~/IntelRSD/intelRSD-2-2-mod-01/PSME/build$ cd /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/build/bin
user@psme1:~/IntelRSD/intelRSD-2-2-mod-01/PSME/build/bin$ ./psme-compute ../../agent/compute/configuration.json
2018-03-13 19:14:43.554889562 - INFO  - agent - Method getChassisInfo has been registered
2018-03-13 19:14:43.555025022 - INFO  - agent - Method getCollection has been registered
2018-03-13 19:14:43.555066812 - INFO  - agent - Method getDriveInfo has been registered
2018-03-13 19:14:43.555095171 - INFO  - agent - Method getManagersCollection has been registered
2018-03-13 19:14:43.555121378 - INFO  - agent - Method getTasksCollection has been registered
2018-03-13 19:14:43.555153840 - INFO  - agent - Method getManagerInfo has been registered
2018-03-13 19:14:43.555179836 - INFO  - agent - Method getTaskInfo has been registered
2018-03-13 19:14:43.555205586 - INFO  - agent - Method getTaskResultInfo has been registered
2018-03-13 19:14:43.555231275 - INFO  - agent - Method getMemoryInfo has been registered
2018-03-13 19:14:43.555261378 - INFO  - agent - Method getNetworkInterfaceInfo has been registered
2018-03-13 19:14:43.555287505 - INFO  - agent - Method getNetworkDeviceInfo has been registered
2018-03-13 19:14:43.555313645 - INFO  - agent - Method getNetworkDeviceFunctionInfo has been registered
2018-03-13 19:14:43.555344336 - INFO  - agent - Method getProcessorInfo has been registered
2018-03-13 19:14:43.555370120 - INFO  - agent - Method getStorageControllerInfo has been registered
2018-03-13 19:14:43.555395582 - INFO  - agent - Method getStorageSubsystemInfo has been registered
2018-03-13 19:14:43.555425831 - INFO  - agent - Method getComputerSystemInfo has been registered
2018-03-13 19:14:43.555457645 - INFO  - agent - Method setComponentAttributes has been registered
2018-03-13 19:14:43.555490147 - INFO  - agent - Method getTrustedModuleInfo has been registered
2018-03-13 19:14:43.555516100 - INFO  - agent - Method deleteTask has been registered
2018-03-13 19:14:43.555551208 - INFO  - agent - Method getMetricDefinitionInfo has been registered
2018-03-13 19:14:43.555581378 - INFO  - agent - Method getMetricDefinitionsCollection has been registered
2018-03-13 19:14:43.555607962 - INFO  - agent - Method getMetrics has been registered
2018-03-13 19:14:43.555632262 - INFO  - agent - Method getFanInfo has been registered
2018-03-13 19:14:43.555661589 - INFO  - agent - Method getPowerZoneInfo has been registered
2018-03-13 19:14:43.555687022 - INFO  - agent - Method getThermalZoneInfo has been registered
2018-03-13 19:14:43.559782872 - INFO  - compute-agent - MANUAL PSME BUILD; Built 19:10:39, 13-03-2018
2018-03-13 19:14:43.560001577 - DEBUG - configuration - Added file ../../agent/compute/configuration.json
2018-03-13 19:14:43.560232284 - WARN  - configuration - Cannot load default file
2018-03-13 19:14:43.560312618 - INFO  - configuration - Load file
2018-03-13 19:14:43.560516022 - INFO  - configuration - Loaded file ../../agent/compute/configuration.json
2018-03-13 19:14:43.560676943 - INFO  - configuration - Load internal defaults
2018-03-13 19:14:43.560962293 - INFO  - compute-agent - JSON Schema load!
2018-03-13 19:14:43.565033606 - INFO  - compute-agent - 
Running SDV PSME Compute Agent.
2018-03-13 19:14:43.565448017 - DEBUG - registration - Registration url: http://localhost:8383 interval: 3s
2018-03-13 19:14:43.565474096 - INFO  - eventing - Starting EventDispatcher thread...
2018-03-13 19:14:43.566003251 - WARN  - db - Cannot check /var/opt/psme/check_PKQ5PJ:: Permission denied
2018-03-13 19:14:43.566328943 - INFO  - db - Database in temporary /tmp/database_X1pEqD
2018-03-13 19:14:43.576606433 - INFO  - default - Service UUID 90586af4-f5c9-11e7-b8b5-1f87effca6f1.
2018-03-13 19:14:43.597648938 - DEBUG - registration - Registration response: {"ipv4address":"localhost","port":5567,"version":"1.0.0"}
2018-03-13 19:14:43.598637496 - INFO  - registration - Agent has been registered to http://localhost:8383, interval 3s, rest runs for 0s
2018-03-13 19:14:43.598687543 - INFO  - eventing - Sending AMC notifications enabled.
Invalid user name
Error: Unable to establish LAN session
Error: Unable to establish IPMI v1.5 / RMCP session
2018-03-13 19:14:46.606718867 - INFO  - agent - gpio minimal read interval: 5000ms
2018-03-13 19:14:46.606966546 - DEBUG - worker - Schedule periodic task state_update:192.168.1.106:0 delay: 0 period: 5000000000
2018-03-13 19:14:46.606994086 - DEBUG - worker - Schedule periodic task power_state_boot_options:192.168.1.106:1 delay: 0 period: 5000000000
2018-03-13 19:14:46.607026317 - DEBUG - worker - Schedule self sheduling task telemetry_runner:192.168.1.106:2 delay: 0
2018-03-13 19:14:46.607059935 - DEBUG - default - Waiting for interrupt signal...
2018-03-13 19:14:46.607147778 - DEBUG - compute-agent - reading presence on slot: 1
2018-03-13 19:14:46.607192184 - INFO  - bmc -  (192.168.1.106:623) in state: ABSENT received event: Inserted
2018-03-13 19:14:46.607250876 - INFO  - bmc -  (192.168.1.106:623) state transition ABSENT --> OFFLINE caused by Inserted
2018-03-13 19:14:46.607261761 - INFO  - bmc -  (192.168.1.106:623) transition status: OK
2018-03-13 19:14:46.607266896 - DEBUG - compute-agent - reading online state...
2018-03-13 19:14:46.616410610 - DEBUG - compute-agent - reading online state error: Can't open IPMI connection.
2018-03-13 19:14:49.605623950 - DEBUG - registration - Rest runs for 6s
Invalid user name
Error: Unable to establish LAN session
Error: Unable to establish IPMI v1.5 / RMCP session
2018-03-13 19:14:51.607091212 - DEBUG - compute-agent - reading presence on slot: 1
2018-03-13 19:14:51.607102919 - DEBUG - compute-agent - reading online state...
2018-03-13 19:14:51.615728809 - DEBUG - compute-agent - reading online state error: Can't open IPMI connection.
2018-03-13 19:14:52.606837259 - DEBUG - registration - Rest runs for 9s
2018-03-13 19:14:55.607373464 - DEBUG - registration - Rest runs for 12s
Invalid user name
Error: Unable to establish LAN session
Error: Unable to establish IPMI v1.5 / RMCP session
2018-03-13 19:14:56.607076105 - DEBUG - compute-agent - reading presence on slot: 1
2018-03-13 19:14:56.607086335 - DEBUG - compute-agent - reading online state...
2018-03-13 19:14:56.616048044 - DEBUG - compute-agent - reading online state error: Can't open IPMI connection.



-----------------------------------------------------------

**Comment by tbykowsk** [comment] 2018-03-14 06:52
Thank you for checking @housemic,

Do you start the PSME Agent as root? I see that only root has read/write access to your `psme-key`.

If it does not help, could you copy `/home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute/configuration.json` to `/etc/psme`, and then run the agent using `./psme-compute /etc/psme/configuration.json`? Maybe the problem is in resolving a relative path.

**Comment by housemic** [comment] 2018-03-16 06:36
Dear  tbykowsk,
I use root to start PSME REST Server and PSME Compute Agent,
and  copy /home/user/IntelRSD/intelRSD-2-2-mod-01/PSME/agent/compute/configuration.json to /etc/psme, and then run the agent using ./psme-compute /etc/psme/configuration.json,

it pass, no error : Invalid User name.

The question can be closed, thank you.
House

**Closed** 2018-03-16 06:41 UTC
Labels: PSME, question
